//
//  AISuggestion.swift
//  AIAnalyzer
//
//  Created by Johnson Elangbam on 29/04/26.
//

import Foundation

/// `AISuggestion` is a data model that encapsulates the final output of an AI analysis request.
///
/// It stores the structured feedback received from an LLM, including:
/// - A high-level diagnosis of the detected code smell.
/// - Detailed, actionable refactoring steps or code examples.
/// - The original metadata (rule name, class name, severity) to maintain traceability back
///   to the initial static analysis finding.
///
/// This object is consumed by the `AISuggestionFormatter` to produce user-friendly console output.
public struct AISuggestion {
    /// The name of the rule that was violated.
    public let ruleName: String
    
    /// The name of the class where the violation occurred.
    public let className: String
    
    /// The severity of the original finding.
    public let severity: Severity
    
    /// A short diagnosis provided by the AI.
    public let diagnosis: String
    
    /// The detailed refactoring guidance or code generated by the AI.
    public let suggestedRefactor: String

    /// Initializes a new AI suggestion.
    /// - Parameters:
    ///   - ruleName: The violated rule.
    ///   - className: The target class name.
    ///   - severity: Violation severity.
    ///   - diagnosis: Summary diagnosis.
    ///   - suggestedRefactor: Detailed AI text.
    public init(
        ruleName: String,
        className: String,
        severity: Severity,
        diagnosis: String,
        suggestedRefactor: String
    ) {
        self.ruleName = ruleName
        self.className = className
        self.severity = severity
        self.diagnosis = diagnosis
        self.suggestedRefactor = suggestedRefactor
    }
}
