//
//  AISuggestion.swift
//  AIAnalyzer
//
//  Created by Johnson Elangbam on 29/04/26.
//

import Foundation

/// `AISuggestion` is a data model that encapsulates the final output of an AI analysis request.
///
/// It stores the structured feedback received from an LLM, including:
/// - A high-level diagnosis of the detected code smell.
/// - Detailed, actionable refactoring steps or code examples.
/// - The original metadata (rule name, class name, severity) to maintain traceability back
///   to the initial static analysis finding.
///
/// This object is consumed by the `AISuggestionFormatter` to produce user-friendly console output.
public struct AISuggestion {
    /// Metadata about the original issue that prompted the AI suggestion.
    public struct IssueMetadata {
        /// The name of the rule that was violated.
        public let ruleName: String
        /// The name of the type where the violation occurred.
        public let typeName: String
        /// The severity of the original finding.
        public let severity: Severity

        public init(
            ruleName: String,
            typeName: String,
            severity: Severity
        ) {
            self.ruleName = ruleName
            self.typeName = typeName
            self.severity = severity
        }
    }

    /// The AI-generated content of the suggestion.
    public struct AIContent {
        /// A short diagnosis provided by the AI.
        public let diagnosis: String
        /// The name/type of the AI model that generated this suggestion.
        public let modelSource: String
        /// The detailed refactoring guidance or code generated by the AI.
        public let suggestedRefactor: String

        public init(
            diagnosis: String,
            modelSource: String,
            suggestedRefactor: String
        ) {
            self.diagnosis = diagnosis
            self.modelSource = modelSource
            self.suggestedRefactor = suggestedRefactor
        }
    }

    /// Metadata about the original issue.
    public let metadata: IssueMetadata
    /// The AI-generated content.
    public let content: AIContent

    /// Initializes a new AI suggestion.
    public init(
        metadata: IssueMetadata,
        content: AIContent
    ) {
        self.metadata = metadata
        self.content = content
    }
}

