//
//  OllamaProvider.swift
//  AIAnalyzer
//
//  Created by Johnson Elangbam on 30/04/26.
//

import Foundation

/// Concrete provider for local AI inference using a running Ollama instance.
public struct OllamaProvider: AIProvider {
    private let endpoint: String
    private let modelName: String

    public init(endpoint: String, modelName: String) {
        self.endpoint = endpoint
        self.modelName = modelName
    }

    public func suggest(for context: AIRequestContext) async throws -> AISuggestion {
        let prompt = buildPrompt(for: context)
        let responseText = try await callOllama(prompt: prompt)

        return AISuggestion(
            ruleName: context.issue.ruleName,
            className: context.classInfo?.name ?? "Unknown",
            severity: context.issue.severity,
            diagnosis: "Local analysis generated by Ollama.",
            modelSource: "Local (Ollama: \(modelName))",
            suggestedRefactor: responseText
        )
    }

    private func buildPrompt(for context: AIRequestContext) -> String {
        let className = context.classInfo?.name ?? "UnknownClass"
        return """
        You are a senior Swift architect.
        Analyze this finding and provide concise, actionable refactor guidance.

        Rule: \(context.issue.ruleName)
        Severity: \(context.issue.severity.rawValue)
        Issue message: \(context.issue.message)
        Class: \(className)

        Code snippet:
        \(context.sourceSnippet)

        Return:
        1) Root cause (1-2 lines)
        2) Refactor steps (3-5 bullets)
        3) Quick win (1 bullet)
        """
    }

    private func callOllama(prompt: String) async throws -> String {
        guard let url = URL(string: endpoint) else {
            throw AIProviderError.invalidConfiguration("Invalid Ollama URL: \(endpoint)")
        }

        var request = URLRequest(url: url)
        request.httpMethod = "POST"
        request.setValue("application/json", forHTTPHeaderField: "Content-Type")
        request.timeoutInterval = 300

        let body: [String: Any] = [
            "model": modelName,
            "messages": [
                ["role": "user", "content": prompt]
            ],
            "stream": false
        ]

        request.httpBody = try JSONSerialization.data(withJSONObject: body)

        do {
            let (data, response) = try await URLSession.shared.data(for: request)

            if let code = (response as? HTTPURLResponse)?.statusCode, !(200...299).contains(code) {
                let bodyText = String(data: data, encoding: .utf8) ?? "<empty>"
                throw AIProviderError.requestFailed("Ollama HTTP \(code): \(bodyText)")
            }

            return try parseText(from: data)
        } catch let error as AIProviderError {
            throw error
        } catch {
            throw AIProviderError.requestFailed("Ollama Error: \(error.localizedDescription)")
        }
    }

    private func parseText(from data: Data) throws -> String {
        guard
            let json = try JSONSerialization.jsonObject(with: data) as? [String: Any],
            let choices = json["choices"] as? [[String: Any]],
            let firstChoice = choices.first,
            let message = firstChoice["message"] as? [String: Any],
            let text = message["content"] as? String
        else {
            throw AIProviderError.invalidResponse
        }

        return text
    }
}
